const dataPointsObject = [
  'stats.visionScore',
  'stats.longestTimeSpentLiving',
  'stats.kills',
  'stats.damageDealtToObjectives',
  'stats.totalDamageTaken',
  'stats.damageSelfMitigated',
  'stats.assists',
  'stats.totalDamageDealtToChampions',
  'stats.visionWardsBoughtInGame',
  'stats.deaths',
  'stats.win',
  'stats.firstBloodAssist',
  'stats.magicDamageDealtToChampions',
  'stats.totalTimeCrowdControlDealt',
  'stats.tripleKills',
  'stats.neutralMinionsKilled',
  'stats.damageDealtToTurrets',
  'stats.physicalDamageDealtToChampions',
  'stats.largestMultiKill',
  'stats.wardsKilled',
  'stats.largestKillingSpree',
  'stats.quadraKills',
  'stats.teamObjective',
  'stats.magicDamageDealt',
  'stats.neutralMinionsKilledTeamJungle',
  'stats.magicalDamageTaken',
  'stats.firstInhibitorKill',
  'stats.trueDamageTaken',
  'stats.combatPlayerScore',
  'stats.largestCriticalStrike',
  'stats.goldSpent',
  'stats.trueDamageDealt',
  'stats.physicalDamageDealt',
  'stats.physicalDamageTaken',
  'stats.objectivePlayerScore',
  'stats.totalDamageDealt',
  'stats.neutralMinionsKilledEnemyJungle',
  'stats.wardsPlaced',
  'stats.turretKills',
  'stats.firstBloodKill',
  'stats.trueDamageDealtToChampions',
  'stats.goldEarned',
  'stats.killingSprees',
  'stats.unrealKills',
  'stats.firstTowerAssist',
  'stats.firstTowerKill',
  'stats.champLevel',
  'stats.doubleKills',
  'stats.inhibitorKills',
  'stats.firstInhibitorAssist',
  'stats.pentaKills',
  'stats.totalHeal',
  'stats.totalMinionsKilled',
  'stats.timeCCingOthers',
  'timeline.goldPerMinDeltas[0-10]',
  'timeline.goldPerMinDeltas[10-20]',
  'timeline.creepsPerMinDeltas[0-10]',
  'timeline.creepsPerMinDeltas[10-20]',
  'timeline.xpPerMinDeltas[0-10]',
  'timeline.xpPerMinDeltas[10-20]',
  'timeline.damageTakenPerMinDeltas[0-10]',
  'timeline.damageTakenPerMinDeltas[10-20]',
];

const TIERS = {
  CHALLENGER: 9,
  GRANDMASTER: 8,
  MASTER: 7,
  DIAMOND: 6,
  PLATINUM: 5,
  GOLD: 4,
  SILVER: 3,
  BRONZE: 2,
  IRON: 1,
  UNRANKED: 0,
}

module.exports = {
  dataPointsObject,
  TIERS,
};
